### ISSUE TITLE
Option - repeatable validator not working with others

### ISSUE THREAD

**Issue by edosrecki** [mattallty/Caporal.js#162]
**Describe the bug**
When using `REPEATABLE` validator for an option, it is not possible to combine it with other validators, for example `INT`.

**To Reproduce**
```js
program
  .command('command')
  .option('-k, --key <val>', '', program.REPEATABLE | program.INT)
  .action((args, opts) => {
    console.log({ args, opts })
  })
```

Running `command -k 1 -k 2 -k 3` logs:
```
{ args: {}, opts: { key: 1 } }
```

**Expected behavior**
Expected to log:
```
{ args: {}, opts: { key: [1, 2, 3] } }
```

**Environment informations (please complete the following information):**
 - OS: MacOS
 - OS version: 10.13.6
 - Shell: fish
 - Caporal version: 1.3.0

**Additional context**
There is a work-around for the problem to use `program.LIST | program.INT` instead of `program.REPEATABLE | program.INT`.

**Comment by mattallty** [comment]
Hey there - I've released `beta` of the next Caporal (`v2`). The v2 is a full rewrite of Caporal in Typescript. This issue should be addressed in v2.

Be warned that, while most of the usage remain the same, the v2 is **not** backward compatible with v1.

**This specific error should be fixed with v2 by using variadic notation + program.NUMERIC**

You can test it with `npm install @caporal/core@beta`

- Docs are available here: https://beta.caporal.io 
- You may want to be specifically interested in the  **migration guide** located here: https://beta.caporal.io/guide/migration.html

Feel free to open issues regarding v2. I would also be happy if you have any feedbacks / suggestions.
