### ISSUE TITLE
logger.error may not be synchronous

### ISSUE THREAD

**Issue by jhorbulyk** [mattallty/Caporal.js#167]
**Describe the bug**
[Observe how exceptions thrown from actions](https://github.com/mattallty/Caporal.js/blob/master/lib/program.js#L85-L92):
* The message from the exception is logged as an error
* The process is exitted with `process.exit(2)`.

The above works correctly, when logging the error is synchronous, however it does not work when logging the error is asynchronous.  [The node.js documentation for `process.exit()` warns about this exact case.](https://nodejs.org/docs/latest-v12.x/api/process.html#process_process_exit_code)   It is possible to trigger this behavior in environments where [`process.stderr` is not synchronous](https://nodejs.org/docs/latest-v12.x/api/process.html#process_process_stdout).

**To Reproduce**
Run the below on a POSIX system

```js
// Javascript code using caporal in sample.js
const prog = require('caporal');
prog
  .command('demo', 'Demo Command')
  .action(function(args, options, logger) {
      const errorString = (new Array(1000*1000)).join('abcdefghijklmnopqrstuvwxyz\n');
      throw new Error(errorString);
  });

prog.parse(process.argv);
```
Invoke with:
```
node sample.js demo 2>  >(cat > file)
```

**Expected behavior**
The expectation is that file will have 1000*1000-1 rows where each row has the entire alphabet.  However, on my system, there are only 3034 rows and the last one is truncated at `abcdefg`.

**Environment informations (please complete the following information):**
 - OS: Ubuntu 
 - OS version: 16.04
 - Shell: bash
 - Caporal version: 1.3.0

**Comment by mattallty** [comment]
Hey there - I've released `beta` of the next Caporal (`v2`). The v2 is a full rewrite of Caporal in Typescript. This issue should be addressed in v2.

Be warned that, while most of the usage remain the same, the v2 is **not** backward compatible with v1.

**This specific error should be fixed with v2 as it now uses process.exitCode**

(BTW, the exist code is now `1`, instead of `2` previously).

You can test it with `npm install @caporal/core@beta`

- Docs are available here: https://beta.caporal.io 
- You may want to be specifically interested in the  **migration guide** located here: https://beta.caporal.io/guide/migration.html

Feel free to open issues regarding v2. I would also be happy if you have any feedbacks / suggestions.
