### ISSUE TITLE
Create a new stable version

### ISSUE THREAD

**Issue by VasiliDarozhkin** [mattallty/Caporal.js#234]
Hello!

Could you please create a new stable version?

Version 2.0.2 that is the most recent stable version doesn't have some changes, for example - updated lodash version

Thank you!

**Comment by VasiliDarozhkin** [comment]
@mattallty Would that be possible? Thank you!

**Comment by hwinkler** [comment]
Caporal released on `npm` has become a significant security risk, through its dependencies. `snyk test` reports many high sev issues in lodash, chalk, ansi-regex... maybe others.

We do need a new build, please, with updated dependencies.

Additionally, please consider using ^ in the semver for the dependencies, so that you won't need to kick out a new build every time they discover a vulnerability in one of the dependencies.

Thank you for Caporal!

**Comment by waheedahmed** [comment]
Same issue with us as well, any chance we get a new version? Thanks!

**Comment by mattallty** [comment]
I'm working on it - CI is currently broken so that's a blocker but I'm gonna spend some time to fix it this weekend

**Comment by mattallty** [comment]
@VasiliDarozhkin @hwinkler if you still use this package, please try installing `@caporal/core@next` and tell me if it's working well for you, thanks !

**Comment by mattallty** [comment]
3.0 has been released with updated deps: https://www.npmjs.com/package/@caporal/core
