### ISSUE TITLE
Have an option check for existence?

### ISSUE THREAD

**Issue by samtstern** [mattallty/Caporal.js#68]
I have this right now:

```javascript
.option("--json", "Output indexes in JSON format", prog.BOOL, false)
```

I'd like `command --json` to be interpreted as `command --json=true` but it does not be the same.  Is there a way to enable this?

**Comment by mAAdhaTTah** [comment]
I would like this as well and would be happy to work on a PR with some guidance.

**Comment by mattallty** [comment]
Hi, it *should* work like you expect, will try to fix it this week end !

**Comment by karlitos** [comment]
If no option argument equals true by default it leads to misleading error messages. I have a validator function which checks if the option equals to 'true' and than throws an error, but the resulting erro message is:

   Error: Invalid value 'true' for option -f.
   Error: You have to choose one of these formats: html,pdf,yaml,docx,png,all

As a user i would be like: "I did not type true" 😕 

It would be good if we can distinguish between options without arguments returning true by default and options with required arguments

**Comment by mattallty** [comment]
What's your use case @karlitos ? Do you have some sample code ?

**Comment by karlitos** [comment]
If I as a use will type `myprog  sourcefile.src -o` the output format value will be true. Wthis does not make sense and the resulting error message is confusing for the user. 

>  Error: Invalid value 'true' for option -o.

```javascript

const outOptionValidator = (opt, defaultPath = DEFAULT_OUTPUT_PATH) => {

	const dir = path.resolve(process.cwd(), opt === true ? defaultPath : opt);

...

}


program.version(require('./package.json').version, '-v, --version')
	.command('build', 'Build your data to the destination format(s).')
	.argument('<source>', 'The path to the source data file.')
	.option('-f, --format <format>', 'Set output format (HTML|PDF|YAML|DOCX|PNG|ALL)', formatOptionValidator, 'all')
	.option('-o, --out <directory>', 'Set output directory', outOptionValidator, DEFAULT_OUTPUT_PATH)

...

````

**Comment by mattallty** [comment]
@karlitos 

The branch [opt-validation-improvements ](https://github.com/mattallty/Caporal.js/tree/opt-validation-improvements) should solve your problems.

For you example, passing `-f` without value should trigger the following message:
`Invalid value (empty) for option -f.`

Additionally, if you throw any `Error` in your validator, the error message will be append to the message: `Invalid value (empty) for option -f. My additional error message here.`

Please note that you will still Caporal still pass the value `true` to your validator, due to the arg parser.

**Comment by karlitos** [comment]
Thanks, I will try it asap, I have to link my project against that branch first
